### ISSUE TITLE
TsType of properties should be intelligent

### ISSUE THREAD

**Issue by andreespirela** [denoland/deno_doc#160]
Right now, if a property doesn't explicitly specify a type ex: ```const var: Type = ...`, `deno_doc` doesn't populate the `tsType` field for it.

Sometimes, type is not needed as it can be guessed by the IDE and the typescript compiler as well

```
const type = "it's a string";
```
in that scenario, it's known that the default type of that variable is string, thus `tsType` should use such.

**Comment by kitsonk** [comment]
This is really broad issue, and would be hard to tackle as a whole.

Actually your example works already:

```
export const a = "a";
```

Will get you a variable named `a` with a type of `"a"`.  The tests for it are here: https://github.com/denoland/deno_doc/blob/main/src/tests.rs#L1317

Non-simple types are not currently supported.  I was going to open up some issues to infer types for specific structures.  There is already a request at #92 for object literals.

So my opinion is that this issue is to broad and unactionable.

**Comment by kitsonk** [comment]
As mentioned, I have opened up other issues that are more narrow with specific cases we can try to tackle.  I am going to close this in lieu of those other issues.
