### ISSUE TITLE
Re-exported symbols via object notation not handled

### ISSUE THREAD

**Issue by surma** [denoland/deno_doc#247]
[`oak-session`](https://deno.land/x/oak_sessions@v3.2.5/mod.ts) uses the export object notation, which makes the module appear empty on [`doc.deno.land`](https://doc.deno.land/https://deno.land/x/oak_sessions@v3.2.5/mod.ts).

**Comment by kitsonk** [comment]
I have been digging into this.  The export object notation is handled.  For example the following would work as expected:

```ts
const foo = "foo";

export { foo };
```

The problem is things like the following are not being handled:

```ts
import foo from "./foo.ts";

export { foo };
```

The import is being tracked, but the reexport logic doesn't seem to be properly tracking the re-exported symbol.

**Comment by kitsonk** [comment]
It also appears to be limited to default imports, as the following works:

```ts
import { foo } from "./foo.ts";

export { foo };
```

**Comment by kitsonk** [comment]
Sorry for the stream of concious here, but the problem is that there is a bug when searching for the bound symbol, when the re-exports are mapped, it is putting the local symbol, not the imported symbol.  For example this breaks also:

```ts
import { foo as f } from "./foo.ts";

export { f };
```

**Comment by kitsonk** [comment]
That change has been upstreamed to docland and I have confirmed [oak-sessions doc](https://doc.deno.land/https://deno.land/x/oak_sessions@v3.2.5/mod.ts) now renders as expected now.
