### ISSUE TITLE
Display referenced non-exported type symbols

### ISSUE THREAD

**Issue by masx200** [denoland/deno_doc#277]
https://doc.deno.land/https://deno.land/x/masx200_leetcode_test@8.2.0/design-skiplist/index.ts/~/default

https://doc.deno.land/https://deno.land/x/masx200_leetcode_test@8.2.0/design-skiplist/index.ts

https://deno.land/x/masx200_leetcode_test@8.2.0/design-skiplist/index.ts?code

```ts
interface Skiplist {
    search: (target: number) => boolean;
    add: (num: number) => void;
    erase: (num: number) => boolean;
}

function Skiplist(): Skiplist {
    const storage = new Map<number, number>();

    function search(target: number): boolean {
        return storage.has(target) && (storage.get(target) || 0) > 0;
    }

    function add(num: number): void {
        storage.set(num, 1 + (storage.get(num) || 0));
    }

    function erase(num: number): boolean {
        if (storage.get(num) === 1) {
            storage.delete(num);

            return true;
        }
        if (search(num)) {
            storage.set(num, -1 + (storage.get(num) || 0));
            return true;
        } else {
            return false;
        }
    }
    return { search, add, erase };
}

export default Skiplist;
```

![Screenshot_2022-08-15-12-34-11-877_com android chrome](https://user-images.githubusercontent.com/34191203/184577550-0469e7bf-f424-4404-be03-fb522bb29a65.jpg)
![Screenshot_2022-08-15-12-34-08-151_com android chrome](https://user-images.githubusercontent.com/34191203/184577553-9e4f8a32-af80-4f74-9920-608e48d54319.jpg)

**Comment by kitsonk** [comment]
Interfaces can't be exported as a default export of a module, and because `interface SkipList` is not exported from the source module, the documentation does not display it, as we only display exported symbols.

We need to consider how to deal with "private" type annotations though when dealing with doc node entries, because TypeScript and language services would allow going to those definitions even if they don't exist.  In the view above, we would expect to be able to link the the `SkipList` as a symbol, even though it isn't exported.

The easiest current work around would be to export the interface, and then it would be available in the documentation.

**Comment by dsherret** [comment]
Another example:

```ts
declare module Test {
  export interface Options {
  }
}

export function test(options: Test.Options): void;
```

Outputs:

```
Defined in file:///.../mod.d.ts:6:0

function test(options: Test.Options): void
```
