### ISSUE TITLE
Doc should support JSDoc link

### ISSUE THREAD

**Issue by iugo** [denoland/deno_doc#45]
https://jsdoc.app/tags-inline-link.html

```js
/**
 * {@link https://docs.github.com/en/free-pro-team@latest/rest doc}
 */
```

should be "[doc](https://docs.github.com/en/free-pro-team@latest/rest)"

not be " {@link https://docs.github.com/en/free-pro-team@latest/rest doc}"

**Comment by jaydenseric** [comment]
Inline links to other documented members in descriptions is absolutely critical, an MVP feature.

There are several variations of the original JSDoc `@link` inline tag, this being the most useful:

```
[`Foo`]{@link Foo}
```

Because you can link whatever markdown formatted text you need in a way consistent with regular markdown links, e.g:

```js
/**
 * Lorem ipsum [dolor sit amet]{@link Foo}, consectetur [adipiscing](https://deno.land) elit.
 */
```

I've used this format extensively to document my npm packages using [`jsdoc-md`](https://github.com/jaydenseric/jsdoc-md): https://github.com/jaydenseric/jsdoc-md#inline-tags .

Example:

- Source: https://github.com/jaydenseric/graphql-upload/blob/bdb5f808e0d514c28c0f59c1abd71680aba29bae/public/Upload.js#L4-L10
- Docs: https://github.com/jaydenseric/graphql-upload#class-upload

Note that TSDoc (which BTW is a very slow work-in-progress, often differs from "standard" JSDoc, and isn't even fully adopted by TypeScript / VS Code) has a take on inline links:

https://tsdoc.org/pages/tags/link

**Comment by crowlKats** [comment]
closing as it is implemented
